# Example Inventory - Copy this file to 'inventory.ini' and adjust IP addresses
#   cp inventory.example.ini inventory.ini

[opi_nodes]
opi01 ansible_host=192.168.1.201
opi02 ansible_host=192.168.1.202
opi03 ansible_host=192.168.1.203
